version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:2023.05@sha256:2c393363a4d5af134254ac9b23ef91602d165167ac7eec9a89f017c7d789d162
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_REGISTRY}" -u "${DOCKER_LOGIN}" --password-stdin
          DOCKER_BUILDKIT=1 docker build \
              -t "${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1}" \
                .
          docker push "${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1}"
          if [ "${CIRCLE_BRANCH}" = "main" ]; then
              docker tag "${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1}" "${DOCKER_REGISTRY}/${DOCKER_REPO}:latest"
              docker push "${DOCKER_REGISTRY}/${DOCKER_REPO}:latest"
          fi

workflows:
  version: 2
  lint-test-build:
    jobs:
      - build-docker-image:
          context:
            - quay-push
